### ISSUE TITLE
Error when running embedding of pages

### ISSUE THREAD

**Issue by macin** [cosmocode/dokuwiki-plugin-aichat#18] opened 2024-10-29 14:29 UTC
### Issue Description

Hi, 
I have started embedding process in CLI. 
Every few lines I see following error

```
2024-10-29 14:25:07
E_WARNING: Trying to access array offset on value of type bool
/var/www/html/lib/plugins/indexmenu/Search.php(701)
#0 /var/www/html/lib/plugins/indexmenu/Search.php(701): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/lib/plugins/indexmenu/Search.php(240): dokuwiki\plugin\indexmenu\Search->customSearch()
#2 /var/www/html/lib/plugins/indexmenu/syntax/indexmenu.php(510): dokuwiki\plugin\indexmenu\Search->search()
#3 /var/www/html/lib/plugins/indexmenu/syntax/indexmenu.php(466): syntax_plugin_indexmenu_indexmenu->buildHtmlIndexmenu()
#4 /var/www/html/lib/plugins/aichat/renderer.php(63): syntax_plugin_indexmenu_indexmenu->render()
#5 /var/www/html/inc/parserutils.php(691): renderer_plugin_aichat->plugin()
#6 /var/www/html/inc/parserutils.php(158): p_render()
#7 /var/www/html/lib/plugins/aichat/Embeddings.php(184): p_cached_output()
#8 /var/www/html/lib/plugins/aichat/Embeddings.php(158): dokuwiki\plugin\aichat\Embeddings->createPageChunks()
#9 /var/www/html/lib/plugins/aichat/cli.php(374): dokuwiki\plugin\aichat\Embeddings->createNewIndex()
#10 /var/www/html/lib/plugins/aichat/cli.php(94): cli_plugin_aichat->createEmbeddings()
#11 /var/www/html/vendor/splitbrain/php-cli/src/Base.php(217): cli_plugin_aichat->main()
#12 /var/www/html/vendor/splitbrain/php-cli/src/Base.php(145): splitbrain\phpcli\Base->execute()
#13 /var/www/html/bin/plugin.php(45): splitbrain\phpcli\Base->run()
#14 /var/www/html/vendor/splitbrain/php-cli/src/Base.php(217): PluginCLI->main()
#15 /var/www/html/vendor/splitbrain/php-cli/src/Base.php(145): splitbrain\phpcli\Base->execute()
#16 /var/www/html/bin/plugin.php(110): splitbrain\phpcli\Base->run()
#17 {main}
```

Is htis something I should be worried about? How can this be fixed?

**Comment by splitbrain** [comment] 2024-10-30 08:24
The issue is caused by the indexmenu plugin. Since it's a warning only, it probably has no effect on the page rendering and the embedding generation. In any case it would need to be fixed in the indexmenu

**Closed by splitbrain** 2024-10-30 08:24 UTC
Labels: bug
